### ISSUE TITLE
How can i make a client in php just like in js

### ISSUE THREAD

**Issue by finguer** [subins2000/Francium-DiffSocket#2]
var conn = new WebSocket('ws://ip:port?service=fa');
conn.send('Hello favio!');

**Comment by subins2000** [comment]
See this example :

https://github.com/subins2000/Francium-DiffSocket/blob/master/tests/services/HelloWorld.php

https://github.com/subins2000/Francium-DiffSocket/blob/master/tests/start-server.php#L9
